# pylint: disable=invalid-name
"""
Django migration file for creating the 'Expense' model in the 'expense' app.
Generated by Django 2.1.15 on 2024-11-19 11:41.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# pylint: disable=invalid-name,line-too-long,missing-module-docstring,missing-class-docstring
class Migration(migrations.Migration):
    """
    Initial migration for the 'expense' app.
    Creates the 'Expense' model.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expense', models.IntegerField()),  # Removed `max_length`, invalid for IntegerField
                ('on', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
